<a href="https://colab.research.google.com/github/Braafisch/Datenfusion-Aufgaben/blob/main/aufgabe_2/aufgabe_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from numpy.linalg import inv
import pandas as pd
from scipy import stats
import requests
import shutil

Messungen mit dem Gerät A: 10.1m, 10.3, 9.5m, 9.8m, 9.4m


Messungen mit dem Gerät B: 11.0m, 10.5m, 9.5m, 10.0m, 9.0m 

Messunsicherheit von A ist 5%

Messunsicherheit von B ist 10%

$$\underline{\hat{x}}=\left(\underline{C}^TR^{-1}\underline{C}\right)^{-1}\underline{C}^TR^{-1}\underline{y}$$

In [2]:
R = np.diagflat(np.append(np.full((1,5),0.05**2),np.full((1,5),0.1**2)))
C = np.ones((10,1))
y = np.array([10.1,10.3,9.5,9.8,9.4,11.0,10.5,9.5,10.0,9.0])
x = np.linalg.multi_dot([np.linalg.inv(np.linalg.multi_dot([C.T,np.linalg.inv(R),C])),C.T,np.linalg.inv(R),y])
print(x)

[9.856]


In [12]:
url = 'https://raw.githubusercontent.com/Braafisch/Datenfusion-Aufgaben/main/aufgabe_2/data_n_Y.dat'
data_path = '/content/data_n_Y.dat'
response = requests.get(url, allow_redirects = True)
with open(data_path, 'wb') as data_fileobj:
  data_fileobj.write(response.content)

data = np.loadtxt(data_path)

In [13]:
y1 = data[:,1]
y2 = data[:,2]
y3 = data[:,3]

In [23]:
y = np.array([np.mean(y1), np.mean(y2), np.mean(y3)], ndmin=2).T
y

array([[ 9.92182725],
       [10.20173718],
       [ 9.76147333]])

In [24]:
C = np.array([[1,1,1]]).T
C

array([[1],
       [1],
       [1]])

In [25]:
R = np.cov([y1,y2,y3], rowvar=1)
R

array([[ 0.91525898,  0.12397294, -0.23751871],
       [ 0.12397294,  2.11038951, -0.32122048],
       [-0.23751871, -0.32122048,  5.19280641]])

In [26]:
x = inv(C.T @ inv(R) @ C) @ C.T @ inv(R) @ y
x

array([[9.96715038]])